
#Script for extracting the input for the parameter fitting 
#procedure from workspace_Simpact.RData (generated by 
#simpact_sim.R)
#---------------------------------------------------------------

par_space1<-function(subdir){
  maindir<-"[PATH_TO_WORK_DIRECTORY_ON_HPC_CLUSTER]"
  destdir<-file.path(maindir,subdir)
  setwd(file.path(destdir))
  load("workspace_Simpact.RData")
  
  #yearly prevalence HIV
  times <-seq(10.25,as.numeric(datalist[[1]]$itable$population.simtime),by=1)
  d=length(times)
  females_alive<-matrix(data=NA,nrow=length(datalist),ncol=d)
  males_alive<-matrix(data=NA,nrow=length(datalist),ncol=d)
  females_infected<-matrix(data=NA,nrow=length(datalist),ncol=d)
  males_infected<-matrix(data=NA,nrow=length(datalist),ncol=d)
  females_HSV2_infected<-matrix(data=NA,nrow=length(datalist),ncol=d)
  males_HSV2_infected<-matrix(data=NA,nrow=length(datalist),ncol=d)
  
  for (i in 1:length(datalist)){
    ptable<-datalist[[i]]$ptable
    ptable_females <- ptable[which(ptable$Gender==1),]
    ptable_males <- ptable[which(ptable$Gender==0),]
    for (j in 1:d){
      females_alive[i,j] <- dim(ptable_females[which(ptable_females$TOB <= times[j] & ptable_females$TOD > times[j]),])[1]  
      males_alive[i,j] <- dim(ptable_males[which(ptable_males$TOB <= times[j] & ptable_males$TOD > times[j]),])[1]
      females_infected[i,j] <- dim(ptable_females[which(ptable_females$TOB <= times[j] & ptable_females$TOD > times[j] & ptable_females$InfectTime < times[j]),])[1]
      males_infected[i,j] <- dim(ptable_males[which(ptable_males$TOB <= times[j] & ptable_males$TOD > times[j] & ptable_males$InfectTime < times[j]),])[1]
      females_HSV2_infected[i,j] <- dim(ptable_females[which(ptable_females$TOB <= times[j] & ptable_females$TOD > times[j] & ptable_females$HSV2InfectTime < times[j]),])[1]
      males_HSV2_infected[i,j] <- dim(ptable_males[which(ptable_males$TOB <= times[j] & ptable_males$TOD > times[j] & ptable_males$HSV2InfectTime < times[j]),])[1]
    }
  }
  females_prevalence <- 100*females_infected/females_alive
  males_prevalence <- 100*males_infected/males_alive
  
  #yearly prevalence HSV2
  females_prevalence_HSV2 <- 100*females_HSV2_infected/females_alive
  males_prevalence_HSV2 <- 100*males_HSV2_infected/males_alive
  
  #HIV prevalence 1989-1998
  prev_HIV_f_estim <- matrix(data=NA,nrow=length(datalist),ncol=10)
  prev_HIV_m_estim <- matrix(data=NA,nrow=length(datalist),ncol=10)
  prev_HIV_f_estim <- females_prevalence[,10:19]
  prev_HIV_m_estim <- males_prevalence[,10:19]
  assign("prev_HIV_f_estim",prev_HIV_f_estim,.GlobalEnv)
  assign("prev_HIV_m_estim",prev_HIV_m_estim,.GlobalEnv)
  #HSV2 prevalence females 1997
  prev_HSV2_f_estim <- vector(mode = "numeric",length=length(datalist))
  prev_HSV2_f_estim <- females_prevalence_HSV2[,18]
  assign("prev_HSV2_f_estim",prev_HSV2_f_estim,.GlobalEnv)
  
  #literature values
  hiv_m_real<-c(0.497,0.928,1.481,1.342,0.918,2.111,1.915,3.383,4.100,3.876)
  hiv_f_real<-c(0.946,1.765,2.818,2.553,1.746,4.015,3.643,6.435,7.800,7.374)
  hsv2_f_real=50.8
  assign("hiv_m_real",hiv_m_real,.GlobalEnv)
  assign("hiv_f_real",hiv_f_real,.GlobalEnv)
  assign("hsv2_f_real",hsv2_f_real,.GlobalEnv)
  
  #relative ssq
  rel_diff_ssq_m=vector(mode="numeric",length=length(datalist))
  rel_diff_ssq_f=vector(mode="numeric",length=length(datalist))
  rel_diff_ssq=vector(mode="numeric",length=length(datalist))
  
  for (k in 1:length(datalist)){
    rel_diff_ssq_m[k]=sum(((hiv_m_real-prev_HIV_m_estim[k,])^2)/(hiv_m_real^2))
    rel_diff_ssq_f[k]=sum(((hiv_f_real-prev_HIV_f_estim[k,])^2)/(hiv_f_real^2)) + ((hsv2_f_real-prev_HSV2_f_estim[k])^2)/(hsv2_f_real^2)
    rel_diff_ssq[k]=rel_diff_ssq_m[k]+rel_diff_ssq_f[k]
  }
  assign("rel_diff_ssq",rel_diff_ssq,.GlobalEnv)
  
  #parameters
  hiv_a<-vector(mode="numeric",length=length(datalist)) 
  hiv_e1<-vector(mode="numeric",length=length(datalist))
  hiv_e2<-vector(mode="numeric",length=length(datalist))
  hiv_f1<-vector(mode="numeric",length=length(datalist))
  for (k in 1:length(datalist)){
    param <- datalist[[k]]$itable
    hiv_a[k] <- param$hivtransmission.param.a
    hiv_e1[k] <- param$hivtransmission.param.e1
    hiv_e2[k] <- param$hivtransmission.param.e2
    hiv_f1[k] <- param$hivtransmission.param.f1
  }
  assign("hiv_a",hiv_a,.GlobalEnv)
  assign("hiv_e1",hiv_e1,.GlobalEnv)
  assign("hiv_e2",hiv_e2,.GlobalEnv)
  assign("hiv_f1",hiv_f1,.GlobalEnv)
  
  #save workspace
  rm(datalist)
  save.image("workspace_par.RData")
}
